services:
  - type: web
    name: vangelo-on-demand
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: TOKEN
        value: "INSERISCI_IL_TUO_TOKEN_TELEGRAM"
