name: Invia Vangelo del Giorno

on:
  workflow_dispatch:  # esecuzione manuale da GitHub
    inputs:
      chat_id:
        description: 'Chat ID Telegram (opzionale, usa variabile env se vuota)'
        required: false
jobs:
  vangelo_job:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Esegui invio Vangelo
        run: |
          echo "✅ TOKEN=$TOKEN"
          echo "✅ CHAT_ID=$CHAT_ID"
          python vangelo_sender.py
