name: Invia Vangelo del Giorno

on:
  workflow_dispatch:  # esecuzione manuale da GitHub
jobs:
  vangelo_job:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}
      CHAT_ID: ${{ secrets.GROUP_CHAT_ID }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Esegui invio Vangelo
        run: python vangelo_sender_TEST.py
